"""Zwift .zwo (workout XML) writer. Maps generated steps 1:1, no re-interpretation."""
import xml.etree.ElementTree as ET


def _step_tag(label: str) -> str:
    if label.startswith("Warmup"):
        return "Warmup"
    if label.startswith("Cooldown"):
        return "Cooldown"
    return "SteadyState"


def build_zwo_workout(workout: dict) -> str:
    """workout: {"goal_label": str, "duration_min": int, "steps": [{"label", "duration_s", "pct_ftp"}, ...]}."""
    steps = workout["steps"]
    name = f"{workout.get('goal_label', 'Workout')} - {workout.get('duration_min', '')} min"

    root = ET.Element("workout_file")
    ET.SubElement(root, "author").text = "Bikeodon"
    ET.SubElement(root, "name").text = name
    ET.SubElement(root, "description").text = "Generated by Bikeodon"
    ET.SubElement(root, "sportType").text = "bike"
    workout_el = ET.SubElement(root, "workout")

    for step in steps:
        tag = _step_tag(step["label"])
        power = round(step["pct_ftp"] / 100, 3)
        el = ET.SubElement(workout_el, tag)
        el.set("Duration", str(int(round(step["duration_s"]))))
        if tag == "SteadyState":
            el.set("Power", str(power))
        else:
            el.set("PowerLow", str(power))
            el.set("PowerHigh", str(power))

    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="unicode")
